services:
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file:
      - .env
volumes:
  data: